sonar.projectKey=dudufritz_ihome-backend
sonar.organization=dudufritz
sonar.projectName=iHome Backend
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,__tests__/**
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=node_modules/**

sonar.host.url=https://sonarcloud.io
